# Generated by Django 4.2.2 on 2024-02-24 17:49

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api_users", "0100_customuser_inactive_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "That email already exists."},
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="inactive_start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Datetime of when the field `is_active` was set False. No value while the field `is_active` is True.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "That phone number already exists."},
                max_length=16,
                null=True,
                unique=True,
                validators=[utils.validators.PhoneNumberValidator()],
            ),
        ),
    ]
